In [1]:
import pandas as pd
df=pd.read_csv("project_data.csv")
df.head(15)

,Student_ID,Computer_Science,Attendance,Study_Hours_Per_Week,Assignment_Score,Internal_Marks,Total_Marks,Average_Marks,Grade,Result,Rank
0,STU0001,50,98,26,60,35,145,48.33,F,Fail,143
1,STU0002,60,88,12,57,42,159,53.00,D,Pass,130
2,STU0003,52,74,26,42,66,160,53.33,D,Pass,129
3,STU0004,93,67,13,81,82,256,85.33,A,Pass,33
4,STU0005,89,80,40,93,38,220,73.33,B,Pass,69
5,STU0006,87,98,18,100,53,240,80.00,A,Pass,49
6,STU0007,64,78,25,78,66,208,69.33,C,Pass,81
7,STU0008,75,82,33,80,43,198,66.00,C,Pass,91
8,STU0009,82,70,40,88,46,216,72.00,B,Pass,73
9,STU0010,39,70,12,50,45,134,44.67,F,Fail,154
10,STU0011,82,83,36,78,80,240,80.00,A,Pass,49
11,STU0012,52,95,4,63,50,165,55.00,D,Pass,124
12,STU0013,59,99,5,99,35,193,64.33,C,Pass,96
13,STU0014,100,83,37,85,97,282,94.00,A+,Pass,8
14,STU0015,47,62,8,58,55,160,53.33,D,Pass,129

In [2]:
df.tail(10)

,Student_ID,Computer_Science,Attendance,Study_Hours_Per_Week,Assignment_Score,Internal_Marks,Total_Marks,Average_Marks,Grade,Result,Rank
990,STU0991,53,86,32,55,63,171,57.00,D,Pass,118
991,STU0992,40,64,11,42,54,136,45.33,F,Fail,152
992,STU0993,75,79,10,84,75,234,78.00,B,Pass,55
993,STU0994,72,70,9,42,88,202,67.33,C,Pass,87
994,STU0995,65,69,14,66,54,185,61.67,C,Pass,104
995,STU0996,63,99,13,89,53,205,68.33,C,Pass,84
996,STU0997,78,97,25,82,100,260,86.67,A,Pass,29
997,STU0998,65,65,2,79,64,208,69.33,C,Pass,81
998,STU0999,92,67,35,77,87,256,85.33,A,Pass,33
999,STU1000,62,82,7,72,68,202,67.33,C,Pass,87

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            1000 non-null   object
 1   Computer_Science      1000 non-null   int64
 2   Attendance            1000 non-null   int64
 3   Study_Hours_Per_Week  1000 non-null   int64
 4   Assignment_Score      1000 non-null   int64
 5   Internal_Marks        1000 non-null   int64
 6   Total_Marks           1000 non-null   int64
 7   Average_Marks         1000 non-null   float64
 8   Grade                 1000 non-null   object
 9   Result                1000 non-null   object
 10  Rank                  1000 non-null   int64
dtypes: float64(1), int64(7), object(3)
memory usage: 86.1+ KB

In [4]:
df.columns

Index(['Student_ID', 'Computer_Science', 'Attendance', 'Study_Hours_Per_Week',
       'Assignment_Score', 'Internal_Marks', 'Total_Marks', 'Average_Marks',
       'Grade', 'Result', 'Rank'],
      dtype='object')

In [5]:
df.describe

<bound method NDFrame.describe of     Student_ID  Computer_Science  Attendance  Study_Hours_Per_Week  \
0      STU0001                50          98                    26
1      STU0002                60          88                    12
2      STU0003                52          74                    26
3      STU0004                93          67                    13
4      STU0005                89          80                    40
..         ...               ...         ...                   ...
995    STU0996                63          99                    13
996    STU0997                78          97                    25
997    STU0998                65          65                     2
998    STU0999                92          67                    35
999    STU1000                62          82                     7

     Assignment_Score  Internal_Marks  Total_Marks  Average_Marks Grade  \
0                  60              35          145          48.33     F
1                  57              42          159          53.00     D
2                  42              66          160          53.33     D
3                  81              82          256          85.33     A
4                  93              38          220          73.33     B
..                ...             ...          ...            ...   ...
995                89              53          205          68.33     C
996                82             100          260          86.67     A
997                79              64          208          69.33     C
998                77              87          256          85.33     A
999                72              68          202          67.33     C

    Result  Rank
0     Fail   143
1     Pass   130
2     Pass   129
3     Pass    33
4     Pass    69
..     ...   ...
995   Pass    84
996   Pass    29
997   Pass    81
998   Pass    33
999   Pass    87

[1000 rows x 11 columns]>