In [2]:
import pandas as pd
df=pd.read_csv("project.csv")
df.head(7)

   Order_ID           Order_Time    Location Food_Item  Quantity  Order_Value
0         1  2025-06-13 03:01:00  Coimbatore   Parotta         2       221.86
1         2  2025-01-27 21:47:00     Chennai  Sandwich         5       428.00
2         3  2025-01-08 02:13:00       Salem     Pizza         1       529.71
3         4  2025-06-16 22:34:00      Trichy    Burger         5       323.08
4         5  2025-01-02 05:44:00     Madurai    Burger         2       277.18
5         6  2025-03-28 03:05:00     Madurai    Burger         3       560.72
6         7  2025-01-12 23:29:00      Trichy      Dosa         1       522.99

In [3]:
df.tail()

     Order_ID           Order_Time Location   Food_Item  Quantity  Order_Value
995       996  2025-05-01 14:32:00    Salem    Sandwich         3       427.34
996       997  2025-03-17 09:10:00    Salem     Biryani         3       650.69
997       998  2025-05-25 08:03:00    Salem  Fried Rice         2       538.19
998       999  2025-06-18 09:51:00  Chennai     Parotta         3       473.87
999      1000  2025-02-02 16:04:00  Madurai     Noodles         3       216.75

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     1000 non-null   int64
 1   Order_Time   1000 non-null   object
 2   Location     1000 non-null   object
 3   Food_Item    1000 non-null   object
 4   Quantity     1000 non-null   int64
 5   Order_Value  1000 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB

In [29]:
df.columns

Index(['Order_ID', 'Order_Time', 'Location', 'Food_Item', 'Quantity',
       'Order_Value'],
      dtype='object')

In [30]:
df.describe()

          Order_ID     Quantity  Order_Value
count  1000.000000  1000.000000  1000.000000
mean    500.500000     3.050000   480.930450
std     288.819436     1.454516   210.398965
min       1.000000     1.000000   120.530000
25%     250.750000     2.000000   298.625000
50%     500.500000     3.000000   476.690000
75%     750.250000     4.000000   665.630000
max    1000.000000     5.000000   848.860000

In [31]:
food = ['Food_Item', 'Order_Value']

df['Total'] = df['Order_Value'].sum(axis=0)

df[['Food_Item', 'Total']].head()

  Food_Item      Total
0   Parotta  480930.45
1  Sandwich  480930.45
2     Pizza  480930.45
3    Burger  480930.45
4    Burger  480930.45